name: Docker Compose Workflow

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and start services
        run: sudo docker compose up -d
